version: '3'

services:
  web:
    build: .
    container_name: my-react-app
    ports:
      - "0.0.0.0:3000:80"
    environment:
      - NODE_ENV=production
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}