version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-react-app
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
