version: "3"
services:
  web:
    image: ${REGISTRY}/cafe-webapp:latest
    container_name: my-react-app
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ${ENV_PATH}/.env:/app/.env
